# Generated by Django 6.1.1 on 2026-09-14 16:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('github_username', models.CharField(blank=True, help_text='e.g., AngelJumbo', max_length=50)),
                ('youtube_channel_url', models.URLField(blank=True, max_length=255)),
                ('twitter_url', models.URLField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True, max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_donated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_supporter', models.BooleanField(default=False, help_text='True if they have donated at least once')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
